### ISSUE TITLE
Spotify API

### ISSUE THREAD

**Issue by MineRickStar** [CodingTrain/Intro-to-Data-APIs-JS#1]
Spotify has an API where you can get all the songs you listened to and all your Playlist. It would be very interesting to see how it can be used.

**Comment by gnrmarcel** [comment]
Yeah!

**Comment by shiffman** [comment]
interesting, I am hoping to avoid dealing with OAuth here, but maybe one API that requires it could be interesting, especially if I can authenticate pretty easily from node.

**Comment by shiffman** [comment]
closing the for next time issues but hope to come back to these!
