### ISSUE TITLE
Strava and Google Local Guides API

### ISSUE THREAD

**Issue by spandl** [CodingTrain/Intro-to-Data-APIs-JS#10]
Similar to the Spotify API, with the Strava API you could get data that you created on your own by uploading runs or rides. 

It would be interesting to learn how any user could authenticate on the fly with the application to visualize the users' own data. Then everybody with a Strava account could see visualization with their own data.

**
With the Google Local Guides Program it could be interesting to track all photos someone uploaded within a certain timeframe, map them out or print them on a timeline. Same thing applies here, if the authentication to the data could be dynamic and part of application, it may have a big impact.

**Comment by spandl** [comment]
I would like to add Unsplash here. Most fabulous free photo database:
https://unsplash.com/developers

**Comment by shiffman** [comment]
closing the for next time issues but hope to come back to these!
