### ISSUE TITLE
Idea: P5js Drawing App With REST API

### ISSUE THREAD

**Issue by anuraghazra** [CodingTrain/Intro-to-Data-APIs-JS#11]
## Drawing App With REST API

Creating a basic drawing app with some server-side features like getting drawings from a database with REST API or Saving user created drawing in database.
basically a CRUD (Create, Read, Update, Delete) drawing application.
we can implement this with [12: Web Sockets and p5.js Tutorial](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6b36TzJidYfIYwTFEq3K5qH)

### Expected Features
- Saving User drawing
- Loading User Drawings
- Viewing Public Drawings
- Updating Drawings
- User Auth? (might be little overwhelming)

### Tools We Can use
- P5js for Client Side
- Nodejs for Back-End (Express)
- Firebase / MongoLab for Saving Drawings
    - Firebase: provides real-time database features
    - Firebase: provides user auth
- Heroku for Nodejs Deployments

### Clicky Stuff
- https://medium.freecodecamp.org/building-a-simple-node-js-api-in-under-30-minutes-a07ea9e390d2
- https://codeburst.io/writing-a-crud-app-with-node-js-and-mongodb-e0827cbbdafb
- https://firebase.google.com
- https://mlab.com
- https://mongoosejs.com/
- https://www.mongodb.com/
- https://heroku.com/

Simple polling app i created using Nodejs, React, mLab
demo : http://quickerpoll.herokuapp.com
source-code: https://github.com/anuraghazra/QuickerPoll

**Comment by shiffman** [comment]
Thanks for this suggestion, I would love to do more about this! It's a bit out of scope for what I've settled on with #12, but I did a challenge about this here (https://thecodingtrain.com/CodingChallenges/045-firebasesavingdrawing.html) and referencing this could be useful!

**Comment by anuraghazra** [comment]
(https://thecodingtrain.com/CodingChallenges/045-firebasesavingdrawing.html)
i don't know how could i forget about this. BTW i am looking forward to this Playlist.

**Comment by joeyklee** [comment]
Hi! @anuraghazra I just wanted to point you also to this example that gives you a very basic layer of authentication onto an express application: https://github.com/joeyklee/very-basic-express-auth-example 

NOTE: generally you'd never want to host your password as a string, but again this is a very basic example of using authentication with express just to show the mechanisms.

**Comment by anuraghazra** [comment]
Yes, thanks for referencing this, i have to dive deeper in the authentication part. i will try to learn these concepts.
