### ISSUE TITLE
Charting Library Example

### ISSUE THREAD

**Issue by joeyklee** [CodingTrain/Intro-to-Data-APIs-JS#14]
From our discussion here -- https://github.com/CodingTrain/Intro-to-Data-APIs-JS/pull/12#issuecomment-470742448 -- and here -- https://github.com/CodingTrain/Intro-to-Data-APIs-JS/pull/12#issuecomment-470750351

We should consider a few things:
1. Making a "classic" chart using a charting library
2. Making a chart with p5 w/ all things considered (e.g. axes, labels, etc)

Some charting library examples:

- https://naver.github.io/billboard.js/
- https://eventbrite.github.io/britecharts/
- https://www.chartjs.org/

**Comment by shiffman** [comment]
There's an example now part of #15 code in #16!

**Comment by shiffman** [comment]
Closing for now as I won't be coming back to this until an expansion or second version of the course!
