### ISSUE TITLE
API Request: Telegram Bot API

### ISSUE THREAD

**Issue by AbelWondafrash** [CodingTrain/Intro-to-Data-APIs-JS#2]
[Telegram](https://en.wikipedia.org/wiki/Telegram_(service)) has a [bot API](https://core.telegram.org/bots) where users can interact with them by sending them messages, commands and **inline** requests and one can even control bots using HTTPS requests to Telegram's bot API. Many enticing areas can they be applied on, ranging from services (like [GmailBot](https://t.me/gmailbot), [GitHubBot](https://t.me/githubbot)) to tools, to games and many more 

It would be great to see how the bot API can be used with **WebHooks** or even _long polling_ for the instant messaging [giant ](http://cdn2.hubspot.net/hub/304927/file-2751796937-png/Assets_COTD/21st-April-2015-Telegram-BBM--WeChat-users-keenest-on-transferring-money.png?t=1481640402152) with active monthly users of over [200 million](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=12&cad=rja&uact=8&ved=2ahUKEwiPv6Xp-qfgAhVEgxoKHaHHBzUQFjALegQIChAB&url=https%3A%2F%2Ftelegram.org%2Fblog%2F200-million&usg=AOvVaw3VQYEfb0D0K8bYFS2-msV3)! **And heavenly, to see how the unique & handy functionality [features (perks)](https://core.telegram.org/bots#5-bot-perks) work.**

![image](https://user-images.githubusercontent.com/17273174/52371572-f9f31900-2a66-11e9-808f-9e17e7058f4e.png)

💚💛❤

**Comment by shiffman** [comment]
This is a great idea but perhaps a bit beyond the scope of what I am trying to show in a beginner / introductory context. Thank you for the suggestion!

**Comment by shiffman** [comment]
You are welcome to re-post this (or I could transfer it if you prefer!) to https://github.com/CodingTrain/Rainbow-Topics/issues.
