### ISSUE TITLE
API Request: Telegra.ph API

### ISSUE THREAD

**Issue by anon-user-1234** [CodingTrain/Intro-to-Data-APIs-JS#3]
[Telegra.ph](https://telegram.org/blog/instant-view#telegraph) is a minimalist publishing tool that allows for creating richly formatted posts and push them to the Web. It has an [API](https://telegra.ph/api) to which queries must be served over HTTPS. _It can be used by anyone and not just Telegram users._

To know that virtually anyone, can create a 'webpage' completely for free is pure bliss by its own and even more useful than so because it can be done more flexibly with code and not requiring manual maintenance. _Take a virtual stock for an online marketing store for instance. You can update your inventory with say a local .csv and a code can update that for you. The applications are endless of course and_ it would be great to see how such an empowering API can be used. 🤗

**Comment by shiffman** [comment]
This is a great idea but perhaps a bit beyond the scope of what I am trying to show in a beginner / introductory context. Thank you for the suggestion!
