### ISSUE TITLE
Exercises for video 2-1

### ISSUE THREAD

**Issue by blinkityblank** [CodingTrain/Intro-to-Data-APIs-JS#30]
- [x] Not an exercise, but I need a screenshot of iTerm
- [x] Serving more than one page in express (with sub-directories)

**Comment by shiffman** [comment]
https://github.com/CodingTrain/Intro-to-Data-APIs-JS/tree/source/module2/exercise_01_multiple_pages

You'll want to capture clicking back and forth between the two pages.
