### ISSUE TITLE
Exercises for video 2-3

### ISSUE THREAD

**Issue by blinkityblank** [CodingTrain/Intro-to-Data-APIs-JS#33]
- [x] Storing data in array on server (mentioned at 14:45 in the video)
- [x] Adding a button to the HTML to send data (mentioned at 15:22 in the video)

**Comment by shiffman** [comment]
These are both in one example 356191c8c8a3de331e379a0a28b24eb7cfa04a07

I think when it comes time to talk about the array, show the server:

<img width="1194" alt="Screen Shot 2019-05-19 at 1 50 37 PM" src="https://user-images.githubusercontent.com/191758/57985985-2098f680-7a3d-11e9-8d3e-7b0a0dbffac0.png">

And then when I talk about the button screen capture clicking the button in the browser. (I actually just did this and will share a capture I made.)
