### ISSUE TITLE
Possible Exercises video 3-2

### ISSUE THREAD

**Issue by blinkityblank** [CodingTrain/Intro-to-Data-APIs-JS#38]
- [x] Better Error Handling
- [x] Better Design or rewriting the paragraph
- [x] Adding/Pulling Different data from Open AQ API

Check out video in playlist for reference

**Comment by shiffman** [comment]
these are all done but it's just one revised version of the project. I think you can show the better error handling by spoofing a lat/lon with no readings and then the different data/rewritten paragraph with a location that has readings. Let me know if you want me to screencap these for you!

**Comment by blinkityblank** [comment]
@shiffman I think it's a short enough moment in the video that I can only show the new text and not show the error handling. It's literally 2 secs in the video.

**Comment by shiffman** [comment]
great!
