### ISSUE TITLE
International Space Station Current Location API

### ISSUE THREAD

**Issue by ngramste** [CodingTrain/Intro-to-Data-APIs-JS#4]
I copied this over from your coding topics issues as I had added this there by mistake.

This is a suggestion for your new Intro to Data APIs playlist. This could be a good first video because of how simple the API is. This API returns the GPS location of the ISS in real time. This is useful for tracking because the ISS's boosts itself into a higher orbit every few weeks to fight crashing back to earth. This causes the orbital period to change making future location predictions invalid.

http://api.open-notify.org/iss-now.json

**Comment by mikakruschel** [comment]
I just modified a bit of "[Coding Challenge #57: Mapping Earthquake Data](https://thecodingtrain.com/CodingChallenges/057-mapping-earthquake-data.html)". 
https://editor.p5js.org/mikakruschel/sketches/ukqfz9bMh

**Comment by shiffman** [comment]
@ngramste thank you for the suggestion! @mikakruschel I noticed you are using a different API https://wheretheiss.at/w/developer. I might like to use this b/c it is `https` (open notify is not). Do you know who maintains this / how reliable it is?

**Comment by mikakruschel** [comment]
I chose the wheretheiss.at API because the p5 web editor doesn't seem to support `fetch()` with `http`.
According to the [about site](https://wheretheiss.at/w/about), the API was developed by Bill Shupp (@shupp), but I do not know how reliable it is.

**Comment by shupp** [comment]
The WTIA API is pretty reliable, been around for many years now.

**Comment by shiffman** [comment]
Oh hi @shupp! Thanks for your wonderful work! How do you feel as me using your API as a demonstration example for a new playlist of tutorial videos I'm planning for https://www.youtube.com/thecodingtrain? Any advice or thoughts welcome!

**Comment by shupp** [comment]
@shiffman That should be fine, thanks for asking.

**Comment by shiffman** [comment]
This is now going to be part of module 1 as seen in #15 and #16!
