### ISSUE TITLE
Make a README file for Weather-Here project for video 3-4

### ISSUE THREAD

**Issue by blinkityblank** [CodingTrain/Intro-to-Data-APIs-JS#40]
The video 3-4 needs a complete README file. 

Mentioned at 11:00 of video 3-4 in playlist

**Comment by shiffman** [comment]
This is here now! https://github.com/CodingTrain/The-Weather-Here 

I'm not sure if I should keep the code for this project in a separate repo and remove it here in this one? I can decide this later. @joeyklee feel free to take a look at how you are credited in the repo linked 👆and pull request any changes!

**Comment by joeyklee** [comment]
@shiffman wow! That's wonderful + super cool. Thanks so much for the nice references everywhere. Much appreciated!
