### ISSUE TITLE
POST and GET requests cannot be made in Windows 10 

### ISSUE THREAD

**Issue by w3dg** [CodingTrain/Intro-to-Data-APIs-JS#42]
![Capture](https://user-images.githubusercontent.com/51162936/62928620-7b40b500-bdd6-11e9-9a5b-a8cdb8ff281b.JPG
I am using Windows 10 with IIS enabled. I am running node.js and live-server. I had tried to follow the tutorial and make the app but the point when we fetch it through the '/api' route, I cannot seem to get it working. I even changed the name of the route and tried but no luck...
Am I missing any configuration or anything else is needed? However, Chrome does not show any error when the website is first loaded...

**Comment by w3dg** [comment]
![Capture](https://user-images.githubusercontent.com/51162936/62929065-5731a380-bdd7-11e9-8018-89169feb90e3.JPG)

**Comment by shiffman** [comment]
Sorry to hear it's not working! The way I built that app you shouldn't also use live-server, just the node server itself. And make sure you are making the correct request to the right port number!

**Comment by debopamgupta** [comment]
Thanks!! I will try it... Thanks to hear from you. I love your videos!!! And from your channel, I have also started following @w3cj @CodingGarden. 😊 I had tried to install http-server but something went wrong... I will try to install it again... BTW I am do not know anything about JS but from your videos, I have learned some basic stuff...

**Comment by w3dg** [comment]
Hey!  The App is now working !! I sourced in the p5.js and p5.dom.js files directly and then ran `node index.js` in the terminal.  I was able to capture the image and send it into the database. Thank you for your precious time and
effort!

**Comment by w3dg** [comment]
![Capture](https://user-images.githubusercontent.com/51162936/63204695-2fcd2600-c0b8-11e9-813a-eea093b0a534.JPG)

**Comment by debopamgupta** [comment]
Thanks for the concern and would like to hear back from you!!
