### ISSUE TITLE
API Request: Creating basic REST API with Nodejs.

### ISSUE THREAD

**Issue by anuraghazra** [CodingTrain/Intro-to-Data-APIs-JS#5]
Creating a basic RESTfull API  with tools like 
- Nodejs
- Express 
- MongoDB

and for deployment we can use [Heroku](https://heroku.com).
and for saving data to cloud we can use  **Database as a service (DBaaS)** for example [mLab](https://mlab.com) / [MongoAtlas](https://www.mongodb.com/cloud/atlas).
this will be a good kickstarter to get started with APIs and understanding how APIs works behind the scenes

**Comment by shiffman** [comment]
I would like to make videos on this! But I think it may be a bit out of scope. . .the database angle is a good one though! Let me try adding this to the README. Related #9

**Comment by shiffman** [comment]
Ok, databases will be in the two new example scenarios added in #12!
