### ISSUE TITLE
Filing some notes from PCDNYC!

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Intro-to-Data-APIs-JS#6]
Thank you @willgeary!

https://transit.land/

**Comment by shiffman** [comment]
https://dsrny.com/project/in-plain-sight

**Comment by shiffman** [comment]
http://geopandas.org/
https://github.com/gboeing/osmnx

**Comment by willgeary** [comment]
Thanks @shiffman ! Here are a few more links from my talk:

TransitFlow: https://github.com/transitland/transitland-processing-animation
Unfolding Maps: http://unfoldingmaps.org/

**Comment by shiffman** [comment]
Keeping these references for possible follow up content, the outline for this playlist is now mostly settled with #15!

**Comment by shiffman** [comment]
closing the for next time issues but hope to come back to these!
