### ISSUE TITLE
Flight tracking & visualization with P5.js ✈

### ISSUE THREAD

**Issue by AbelWondafrash** [CodingTrain/Intro-to-Data-APIs-JS#7]
![image](https://user-images.githubusercontent.com/17273174/52527018-daf8bf00-2cd2-11e9-8b63-300e9665dc72.png)

There are often over 100,000 up to [200,000](https://www.independent.co.uk/travel/news-and-advice/flights-sky-map-worldwide-air-traffic-aviation-busiest-day-june-a8428451.html) flights per day. It would be such a mesmerizing thing to visualize even a few thousand moving around the globe with possible interactivity in P5.js. _Something like [this](https://flightaware.com/live/) but in **3D**_

I've found [this](https://aviation-edge.com/) **free** API which can give up to 3000 and potentially more. But I think even this is surplus. _It returns JSON, _of course_, and it shall be a pretty interesting beginner-friendly area to start with._

Here is my [API_KEY](http://aviation-edge.com/v2/public/flights?key=d0d178-7e0a13&limit=1) 🙈 to save you the time.

Consider [this](https://flightaware.com/commercial/flightxml/) as it may be more rich content wi$e. [**Non-Free**]

**Comment by shiffman** [comment]
Oh, interesting idea for an API thank you!

**Comment by shiffman** [comment]
I'm going to label some of these issues "Part 2" as great ideas if I do a follow-up. This could also be suggested as a Coding Challenge at https://github.com/CodingTrain/Rainbow-Topics/issues. I think this is too complex a project for the current scope of the playlist as described in #12. Thank you for the suggestion!

**Comment by shiffman** [comment]
closing the for next time issues but hope to come back to these!
